/* Modül 1 — Elektrik Yasaları */
ELK_ICERIK[1] = {
teori: `<b style="font-size:15px">🔹 1) Madde, yük ve akımın kaynağı</b><br>Her madde atomlardan oluşur. Atomun merkezinde <b>çekirdek</b> vardır; çekirdekte <b>pozitif yüklü protonlar</b> ve yüksüz <b>nötronlar</b> bulunur. Çekirdeğin çevresindeki yörüngelerde <b>negatif yüklü elektronlar</b> döner. Dış yörüngedeki elektronlar çekirdeğe zayıf bağlıdır; metallerde bu elektronlar atomdan kolayca ayrılıp kristal içinde serbestçe gezer. Bunlara <b>serbest elektron</b> denir ve metal iletkende akımı taşıyan bunlardır.<br><br>Maddeler iletkenlik bakımından üçe ayrılır:<br><b>• İletken:</b> çok sayıda serbest elektronu olan maddeler — bakır, alüminyum, gümüş, altın. Kablo ve bara iletkenleri buradan seçilir.<br><b>• Yalıtkan:</b> serbest elektronu yok denecek kadar az olan maddeler — PVC, XLPE, porselen, cam, kauçuk. Kablo kılıfı, izolatör ve eldiven buradan yapılır.<br><b>• Yarı iletken:</b> iletkenliği sıcaklık ve katkı maddesiyle değişen maddeler — silisyum, germanyum. Diyot, transistör, güneş hücresi bunlardan üretilir.<br><br><b>• Akım yönü:</b> Elektronlar kaynağın (−) ucundan (+) ucuna doğru akar. Devre hesaplarında ise tarihsel alışkanlıkla <b>geleneksel akım yönü</b> kullanılır: dış devrede (+)'dan (−)'ye. Hesap sonucu değişmez, yalnız yön işaretine dikkat edilir.<br><br>

<b style="font-size:15px">🔹 2) Ohm yasası: V = I · R</b><br>Bir iletkenin uçlarındaki gerilim (V, volt), içinden geçen akım (I, amper) ile direncinin (R, ohm) çarpımına eşittir: <b>V = I · R</b>. Buradan <b>I = V / R</b> ve <b>R = V / I</b> elde edilir. Anlamı şudur: sabit dirençte gerilimi iki katına çıkarırsan akım da iki katına çıkar; sabit gerilimde direnci iki katına çıkarırsan akım yarıya iner.<br>Örnek: 24 V ve 8 Ω → I = 24 / 8 = <b>3 A</b>.<br>Örnek: Bir ısıtıcı 230 V'ta 5 A çekiyor → R = 230 / 5 = <b>46 Ω</b>.<br><br>Ohm yasası sıcaklığı sabit metal iletkenler ve dirençler için doğrusaldır (V–I grafiği düz çizgidir). Akkor flaman lamba gibi ısındıkça direnci büyüyen elemanlarda, diyot gibi yarı iletkenlerde bu ilişki doğrusal değildir; o anki değerle hesap yapılır.<br>
<div class="figwrap"><div class="fighead">🔎 Şema 1 — Ohm üçgeni ve V–I doğrusu</div><figure class="fig" style="margin:0;border:none;border-radius:0"><svg viewBox="0 0 460 220"><rect width="460" height="220" fill="#141d26"/><polygon points="40,190 200,190 120,40" fill="none" stroke="#3a4b5c" stroke-width="2"/><line x1="75" y1="125" x2="165" y2="125" stroke="#3a4b5c" stroke-width="2"/><line x1="120" y1="125" x2="120" y2="190" stroke="#3a4b5c" stroke-width="2"/><text x="120" y="110" fill="#ffb000" font-size="22" text-anchor="middle">V</text><text x="92" y="168" fill="#33b1ff" font-size="20" text-anchor="middle">I</text><text x="148" y="168" fill="#f85149" font-size="20" text-anchor="middle">R</text><text x="120" y="210" fill="#8a98ab" font-size="10" text-anchor="middle">Aradığını kapat, kalanı oku</text><line x1="260" y1="190" x2="440" y2="190" stroke="#3a4b5c" stroke-width="2"/><line x1="260" y1="190" x2="260" y2="45" stroke="#3a4b5c" stroke-width="2"/><line x1="260" y1="190" x2="430" y2="60" stroke="#f85149" stroke-width="2"/><line x1="260" y1="190" x2="430" y2="125" stroke="#33b1ff" stroke-width="2"/><text x="400" y="62" fill="#f85149" font-size="10" text-anchor="end">R = 20 Ω</text><text x="440" y="146" fill="#33b1ff" font-size="10" text-anchor="end">R = 10 Ω</text><text x="266" y="42" fill="#8a98ab" font-size="10">V (V)</text><text x="300" y="42" fill="#e8eef6" font-size="10">Dik eğim = büyük R</text><text x="440" y="206" fill="#8a98ab" font-size="10" text-anchor="end">I (A)</text></svg></figure></div><br>
<b>• İletkenin direnci:</b> R = ρ · L / S. ρ (ro) malzemenin özdirenci, L uzunluk (m), S kesit (mm²). Bakır için ρ ≈ 0,0178 Ω·mm²/m (iletkenlik k ≈ 56 m/Ω·mm²), alüminyum için ρ ≈ 0,0286 Ω·mm²/m (k ≈ 35). Metallerde direnç sıcaklıkla artar; bakırda yaklaşık %0,4/°C.<br>Örnek: 20 m uzaklıktaki prize 2,5 mm² bakır hat. Akım gidip döndüğü için iletken boyu 40 m → R = 0,0178 × 40 / 2,5 ≈ <b>0,285 Ω</b>. 16 A'de gerilim düşümü ΔU = 16 × 0,285 ≈ 4,6 V, yani 230 V'un yaklaşık %2'si.<br><br>

<b style="font-size:15px">🔹 3) Seri devre</b><br>Elemanlar art arda, tek bir akım yolu üzerinde bağlıdır.<br><b>• Akım:</b> her elemandan <b>aynı akım</b> geçer.<br><b>• Direnç:</b> R<sub>top</sub> = R1 + R2 + R3 + … (toplam, en büyük dirençten de büyüktür).<br><b>• Gerilim:</b> kaynak gerilimi elemanlara <b>dirençleriyle orantılı</b> bölünür: U = U1 + U2 + … Büyük dirence büyük gerilim düşer (gerilim bölücü: U1 = U · R1 / R<sub>top</sub>).<br><b>• Arıza davranışı:</b> bir eleman koparsa devre tümüyle açılır, hepsi söner (eski tip seri yılbaşı lambaları gibi).<br>
<div class="figwrap"><div class="fighead">🔎 Şema 2 — Seri devre: akım aynı, gerilim bölünür</div><figure class="fig" style="margin:0;border:none;border-radius:0"><svg viewBox="0 0 460 200"><rect width="460" height="200" fill="#141d26"/><line x1="60" y1="50" x2="140" y2="50" stroke="#ffb000" stroke-width="2"/><rect x="140" y="42" width="60" height="16" fill="none" stroke="#f85149" stroke-width="2"/><line x1="200" y1="50" x2="270" y2="50" stroke="#ffb000" stroke-width="2"/><rect x="270" y="42" width="60" height="16" fill="none" stroke="#f85149" stroke-width="2"/><line x1="330" y1="50" x2="400" y2="50" stroke="#ffb000" stroke-width="2"/><line x1="400" y1="50" x2="400" y2="160" stroke="#ffb000" stroke-width="2"/><line x1="400" y1="160" x2="60" y2="160" stroke="#33b1ff" stroke-width="2"/><line x1="60" y1="160" x2="60" y2="107" stroke="#33b1ff" stroke-width="2"/><line x1="60" y1="95" x2="60" y2="50" stroke="#ffb000" stroke-width="2"/><line x1="45" y1="95" x2="75" y2="95" stroke="#e8eef6" stroke-width="3"/><line x1="52" y1="107" x2="68" y2="107" stroke="#e8eef6" stroke-width="3"/><text x="12" y="105" fill="#e8eef6" font-size="11">12 V</text><text x="170" y="34" fill="#e8eef6" font-size="11" text-anchor="middle">R1 = 2 Ω</text><text x="300" y="34" fill="#e8eef6" font-size="11" text-anchor="middle">R2 = 4 Ω</text><text x="170" y="78" fill="#ffb000" font-size="11" text-anchor="middle">U1 = 4 V</text><text x="300" y="78" fill="#ffb000" font-size="11" text-anchor="middle">U2 = 8 V</text><polygon points="400,112 395,100 405,100" fill="#33b1ff"/><text x="408" y="110" fill="#33b1ff" font-size="11">I = 2 A</text><text x="230" y="125" fill="#8a98ab" font-size="10" text-anchor="middle">Akım her noktada aynı; gerilim dirençle orantılı bölünür</text><text x="230" y="186" fill="#e8eef6" font-size="11" text-anchor="middle">I = 12 / (2+4) = 2 A  ·  U1 + U2 = 4 + 8 = 12 V</text></svg></figure></div><br>
Örnek: Aynı iki adet 230 V / 100 W akkor lamba 230 V'a seri bağlanırsa: her birinin direnci R = V² / P = 230² / 100 = 529 Ω; toplam 1058 Ω; akım 230 / 1058 ≈ 0,217 A; toplam güç 230² / 1058 = <b>50 W</b>, lamba başına 25 W. Lambalar sönük yanar; seri bağlantı ev tesisatında bu yüzden kullanılmaz (gerçekte soğuk flamanın direnci daha düşük olduğundan değer biraz farklı çıkar).<br><br>

<b style="font-size:15px">🔹 4) Paralel devre</b><br>Elemanların uçları aynı iki noktaya bağlıdır; her eleman ayrı bir koldur.<br><b>• Gerilim:</b> her kolda <b>aynı gerilim</b> vardır.<br><b>• Akım:</b> ana akım kollara bölünür: I = I1 + I2 + …; küçük dirençli koldan büyük akım geçer.<br><b>• Direnç:</b> 1/R<sub>top</sub> = 1/R1 + 1/R2 + …; iki direnç için kısa yol R<sub>top</sub> = R1·R2 / (R1+R2). Toplam direnç <b>en küçük koldan da küçüktür</b>. n adet eşit direnç R için R<sub>top</sub> = R / n.<br><b>• Arıza davranışı:</b> kollar bağımsızdır; bir lamba patlasa diğerleri yanmaya devam eder.<br><br>Ev tesisatı bu yüzden paraleldir: her cihaz aynı 230 V'u görür, biri bozulunca diğerleri etkilenmez. Ancak her yeni cihaz ana hattan çekilen akımı artırır; sigortanın atması çoğu zaman aynı hatta çok fazla yük toplanmasından kaynaklanır.<br>
<div class="figwrap"><div class="fighead">🔎 Şema 3 — Paralel devre: gerilim aynı, akım bölünür</div><figure class="fig" style="margin:0;border:none;border-radius:0"><svg viewBox="0 0 460 220"><rect width="460" height="220" fill="#141d26"/><line x1="50" y1="40" x2="330" y2="40" stroke="#ffb000" stroke-width="2"/><line x1="50" y1="180" x2="330" y2="180" stroke="#33b1ff" stroke-width="2"/><line x1="50" y1="40" x2="50" y2="104" stroke="#ffb000" stroke-width="2"/><line x1="50" y1="116" x2="50" y2="180" stroke="#33b1ff" stroke-width="2"/><line x1="35" y1="104" x2="65" y2="104" stroke="#e8eef6" stroke-width="3"/><line x1="42" y1="116" x2="58" y2="116" stroke="#e8eef6" stroke-width="3"/><text x="4" y="114" fill="#e8eef6" font-size="11">12 V</text><line x1="200" y1="40" x2="200" y2="85" stroke="#ffb000" stroke-width="2"/><rect x="190" y="85" width="20" height="50" fill="none" stroke="#f85149" stroke-width="2"/><line x1="200" y1="135" x2="200" y2="180" stroke="#33b1ff" stroke-width="2"/><line x1="330" y1="40" x2="330" y2="85" stroke="#ffb000" stroke-width="2"/><rect x="320" y="85" width="20" height="50" fill="none" stroke="#f85149" stroke-width="2"/><line x1="330" y1="135" x2="330" y2="180" stroke="#33b1ff" stroke-width="2"/><text x="218" y="105" fill="#e8eef6" font-size="11">R1 = 6 Ω</text><text x="218" y="122" fill="#33b1ff" font-size="11">I1 = 2 A</text><text x="348" y="105" fill="#e8eef6" font-size="11">R2 = 3 Ω</text><text x="348" y="122" fill="#33b1ff" font-size="11">I2 = 4 A</text><polygon points="130,40 118,35 118,45" fill="#33b1ff"/><text x="80" y="30" fill="#33b1ff" font-size="11">I = 6 A</text><text x="265" y="160" fill="#8a98ab" font-size="10" text-anchor="middle">Her kolda 12 V</text><text x="230" y="205" fill="#e8eef6" font-size="10" text-anchor="middle">Rtop = 6·3/(6+3) = 2 Ω → I = 12/2 = 6 A = I1 + I2</text></svg></figure></div><br>

<b style="font-size:15px">🔹 5) Karışık (seri-paralel) devre çözümü</b><br>Gerçek devrelerde seri ve paralel parçalar bir arada bulunur. Çözüm adımları:<br><b>• Adım 1:</b> En içteki paralel veya seri grubu bul, eşdeğer tek dirence indir.<br><b>• Adım 2:</b> Devre tek bir dirence inene kadar tekrarla, R<sub>top</sub>'u bul.<br><b>• Adım 3:</b> Ana akımı I = U / R<sub>top</sub> ile hesapla.<br><b>• Adım 4:</b> Geriye doğru açarak her grubun gerilimini ve kol akımlarını bul.<br>Örnek: 24 V kaynağa R1 = 4 Ω seri, ardından R2 = 6 Ω ile R3 = 12 Ω paralel bağlı. Paralel grup = 6·12/(6+12) = 4 Ω. R<sub>top</sub> = 4 + 4 = 8 Ω. I = 24 / 8 = <b>3 A</b>. U1 = 3 × 4 = 12 V; paralel grubun gerilimi = 24 − 12 = 12 V. I2 = 12 / 6 = 2 A, I3 = 12 / 12 = 1 A; kontrol: 2 + 1 = 3 A ✓.<br><br>

<b style="font-size:15px">🔹 6) Kirchhoff yasaları</b><br>Ohm yasası tek bir eleman içindir; birden fazla kaynak ve kolu olan devrelerde Kirchhoff yasaları kullanılır.<br><b>• Kirchhoff Akımlar Yasası (KAY):</b> Bir düğüme (birleşme noktasına) giren akımların toplamı, çıkan akımların toplamına eşittir. Yük bir noktada birikmez. Bir dağıtım barasına gelen akım, çıkış hatlarının akımları toplamıdır.<br><b>• Kirchhoff Gerilimler Yasası (KGY):</b> Kapalı bir çevre boyunca kaynak gerilimleri, dirençlerdeki gerilim düşümlerinin toplamına eşittir; çevre boyunca gerilimlerin cebirsel toplamı sıfırdır.<br>
<div class="figwrap"><div class="fighead">🔎 Şema 4 — KAY (düğüm) ve KGY (çevre)</div><figure class="fig" style="margin:0;border:none;border-radius:0"><svg viewBox="0 0 460 230"><rect width="460" height="230" fill="#141d26"/><line x1="230" y1="10" x2="230" y2="220" stroke="#3a4b5c" stroke-dasharray="4 4"/><line x1="20" y1="110" x2="105" y2="110" stroke="#ffb000" stroke-width="2"/><polygon points="100,110 88,105 88,115" fill="#ffb000"/><circle cx="110" cy="110" r="6" fill="#e8eef6"/><line x1="110" y1="110" x2="200" y2="60" stroke="#ffb000" stroke-width="2"/><line x1="110" y1="110" x2="200" y2="160" stroke="#ffb000" stroke-width="2"/><polygon points="200,60 186,62 192,72" fill="#ffb000"/><polygon points="200,160 192,148 186,158" fill="#ffb000"/><text x="22" y="98" fill="#e8eef6" font-size="11">I = 10 A</text><text x="150" y="50" fill="#e8eef6" font-size="11">I1 = 4 A</text><text x="150" y="182" fill="#e8eef6" font-size="11">I2 = 6 A</text><text x="110" y="212" fill="#3fb950" font-size="11" text-anchor="middle">KAY: 10 = 4 + 6</text><rect x="260" y="40" width="180" height="130" fill="none" stroke="#ffb000" stroke-width="2"/><rect x="320" y="32" width="50" height="16" fill="#141d26" stroke="#f85149" stroke-width="2"/><rect x="432" y="80" width="16" height="50" fill="#141d26" stroke="#f85149" stroke-width="2"/><rect x="245" y="92" width="30" height="26" fill="#141d26"/><line x1="245" y1="100" x2="275" y2="100" stroke="#e8eef6" stroke-width="3"/><line x1="252" y1="112" x2="268" y2="112" stroke="#e8eef6" stroke-width="3"/><text x="282" y="110" fill="#e8eef6" font-size="11">24 V</text><text x="345" y="24" fill="#f85149" font-size="11" text-anchor="middle">U1 = 10 V</text><text x="425" y="110" fill="#f85149" font-size="11" text-anchor="end">U2 = 14 V</text><text x="350" y="212" fill="#3fb950" font-size="11" text-anchor="middle">KGY: 24 − 10 − 14 = 0</text></svg></figure></div><br>
Örnek: Bir pano barasından üç çıkış var: 7 A, 5 A ve bilinmeyen bir hat. Ana girişte pens ampermetre 20 A gösteriyor. KAY'a göre üçüncü hat 20 − 7 − 5 = <b>8 A</b> çekiyordur.<br><br>

<b style="font-size:15px">🔹 7) Güç, enerji ve ısınma (Joule yasası)</b><br>Güç birim zamanda harcanan enerjidir, birimi <b>Watt (W)</b>: <b>P = V · I = I² · R = V² / R</b>. Dirençte harcanan güç ısıya dönüşür (Joule etkisi). Enerji W = P · t'dir (Wh veya kWh).<br>Örnek: I = 2 A, R = 10 Ω → P = 2² × 10 = <b>40 W</b>.<br>Örnek: V = 12 V, R = 6 Ω → I = 2 A, P = 12 × 2 = <b>24 W</b>.<br><br><b>• I² etkisi:</b> Aynı dirençte akım 2 katına çıkarsa ısı 4 katına çıkar. Kablo kayıpları ve gevşek bağlantı ısınması bu yüzden akımla hızla büyür.<br>Örnek: Gevşek bir klemenste 0,05 Ω geçiş direnci oluşmuş ve hat 16 A taşıyor: P = 16² × 0,05 = <b>12,8 W</b>. Bu ısı birkaç milimetrelik bir noktada toplanır; klemens kararır, izolasyon erir, yangın başlayabilir.<br><b>🛠 Saha notu:</b> Klemens ve sigorta bağlantılarını üreticinin verdiği sıkma torkuyla sık. Termal kamerayla yük altındaki panoda sıcak nokta taraması yapmak bu arızaları erkenden yakalar.<br><br>

<b style="font-size:15px">🔹 8) Ölçüm bağlantısı ve sık hatalar</b><br><b>• Ampermetre seri bağlanır:</b> akımın yolu üzerine konur, iç direnci çok küçüktür. Paralel (gerilime) bağlanırsa kaynağı kısa devre eder; aletin sigortası atar veya alet yanar. Sahada akımı devreyi açmadan <b>pens ampermetre</b> ile ölçmek daha güvenlidir.<br><b>• Voltmetre paralel bağlanır:</b> ölçülecek iki noktaya bağlanır, iç direnci çok büyüktür.<br><b>• Ohmmetre yalnız enerjisiz devrede</b> kullanılır; enerjili devrede hem yanlış okur hem de alete zarar verir.<br><br>Sık hesap hataları:<br><b>• Paralelde dirençleri toplamak:</b> paralel toplam direnç en küçük koldan küçüktür; toplam büyük çıktıysa hata var.<br><b>• Birimleri karıştırmak:</b> kΩ, mA, kW ön eklerini dönüştürmeden işleme sokmak.<br><b>• Kablo dönüş yolunu unutmak:</b> tek fazlı hatta direnç hesabında iletken boyu gidiş + dönüş (2L) alınır.<br><b>• P = V·I'yi her yerde kullanmak:</b> alternatif akımda endüktif/kapasitif yüklerde güç faktörü (cos φ) devreye girer; bu konu Güç Hesabı modülünde işlenir.<br><br>

<b style="font-size:15px">🔹 9) Dayanak ve kontrol listesi</b><br>Kablo kesiti seçimi, gerilim düşümü, kısa devre akımı ve koruma cihazı seçimi (TS HD 60364 serisi ve Elektrik İç Tesisleri Yönetmeliği hesapları) tamamen bu temel yasalara dayanır. MYK Elektrik Tesisatçısı sınavlarında Ohm yasası, seri/paralel eşdeğer direnç ve güç hesabı temel soru tipleridir.<br><b>• V = I · R;</b> I = V/R; R = V/I.<br><b>• R = ρ · L / S;</b> bakır ρ ≈ 0,0178, alüminyum ≈ 0,0286 Ω·mm²/m.<br><b>• Seri:</b> akım aynı, R<sub>top</sub> = ΣR, gerilim dirençle orantılı bölünür.<br><b>• Paralel:</b> gerilim aynı, 1/R<sub>top</sub> = Σ(1/R), akım bölünür.<br><b>• KAY:</b> düğüme giren = çıkan. <b>KGY:</b> çevrede ΣU = 0.<br><b>• Güç:</b> P = V·I = I²R = V²/R; ısı akımın karesiyle artar.<br><b>• Ölçüm:</b> ampermetre seri, voltmetre paralel, ohmmetre enerjisiz devrede.`,
ozet: `<b>Özet:</b> Atom çekirdeğinde pozitif protonlar ve nötronlar, çevresinde negatif elektronlar bulunur; metallerde akımı serbest elektronlar taşır. Maddeler iletken, yalıtkan ve yarı iletken olarak üçe ayrılır.<br><b>Ohm yasası:</b> V = I·R → I = V/R, R = V/I. Örnek: 24 V / 8 Ω = 3 A.<br><b>İletken direnci:</b> R = ρ·L/S; bakır ρ ≈ 0,0178 Ω·mm²/m (k ≈ 56). Tek fazda boy gidiş+dönüş alınır.<br><b>Seri:</b> R<sub>top</sub> = R1+R2+…; akım aynı; gerilim dirençle orantılı bölünür; biri koparsa hepsi söner.<br><b>Paralel:</b> 1/R<sub>top</sub> = 1/R1+1/R2+…; iki dirençte R1·R2/(R1+R2); gerilim aynı; akım bölünür; kollar bağımsız. Ev tesisatı paraleldir.<br><b>Kirchhoff:</b> KAY — düğüme giren akım = çıkan akım. KGY — kapalı çevrede gerilimlerin toplamı sıfır.<br><b>Güç:</b> P = V·I = I²·R = V²/R (Watt). Örnek: 12 V, 6 Ω → 2 A, 24 W. Akım 2 kat → ısı 4 kat; gevşek klemens bu yüzden yanar.<br><b>Terim:</b> Joule etkisi — dirençte harcanan gücün ısıya dönüşmesi.<br><b>Sık hata:</b> Ampermetreyi paralel bağlamak kısa devre yapar; paralel dirençleri toplamak; ohmmetreyi enerjili devrede kullanmak.`,
sorular: [
{q:"24 V kaynağa 4 Ω seri, ardından 6 Ω ve 12 Ω paralel bağlıdır. Ana akım kaç A'dir?",opts:["2 A","3 A","4 A","6 A"],ans:1,ex:"6||12 = 4 Ω; R_top = 4 + 4 = 8 Ω; I = 24 / 8 = 3 A."},
{q:"Bir düğüme 20 A giriyor, iki çıkış 7 A ve 5 A çekiyor. Üçüncü çıkış kaç A'dir?",opts:["12 A","32 A","2 A","8 A"],ans:3,ex:"KAY: giren = çıkan; 20 − 7 − 5 = 8 A."},
{q:"10 Ω ile 10 Ω paralel bağlanırsa eşdeğer direnç kaçtır?",opts:["5 Ω","20 Ω","10 Ω","1 Ω"],ans:0,ex:"n eşit direnç paralelde R/n: 10/2 = 5 Ω."},
{q:"Gevşek bir klemenste 0,05 Ω geçiş direnci var, hat 16 A taşıyor. Burada ısıya dönüşen güç?",opts:["0,8 W","12,8 W","3,2 W","25,6 W"],ans:1,ex:"P = I²·R = 16² × 0,05 = 256 × 0,05 = 12,8 W."},
{q:"Tek fazlı 20 m'lik hatta iletken direnci hesaplanırken hangi uzunluk alınır?",opts:["10 m","20 m","40 m","60 m"],ans:2,ex:"Akım faz iletkeninden gider nötrden döner; toplam iletken boyu 2 × 20 = 40 m."},
{q:"Kirchhoff Gerilimler Yasası neyi ifade eder?",opts:["Düğüme giren akım çıkana eşittir","Kapalı çevrede gerilimlerin cebirsel toplamı sıfırdır","Direnç sıcaklıkla artar","Güç akımın karesiyle artar"],ans:1,ex:"KGY: kapalı bir çevrede kaynak gerilimleri, gerilim düşümlerinin toplamına eşittir; cebirsel toplam sıfırdır."}
]
};
